version: "3.0"
services:
  app:
    image: akhilmylaram/register:v1
    ports:
      - '80:80'
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.5'
          memory: '500M'


